//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAYTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAYTable()
        {
            this.CTHDTables = new HashSet<CTHDTable>();
            this.SIZEGIAYTables = new HashSet<SIZEGIAYTable>();
        }
    
        public int MAGIAY { get; set; }
        public string TENGIAY { get; set; }
        public string HINHANH { get; set; }
        public string CHITIETSANPHAM { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
        public Nullable<int> KHUYENMAI { get; set; }
        public Nullable<int> GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYTHEM { get; set; }
        public Nullable<int> MATHUONGHIEU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDTable> CTHDTables { get; set; }
        public virtual THUONGHIEUTable THUONGHIEUTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIZEGIAYTable> SIZEGIAYTables { get; set; }
    }
}
