//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONTable()
        {
            this.CTHDTables = new HashSet<CTHDTable>();
        }
    
        public int MAHD { get; set; }
        public string SOHD { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<System.DateTime> NGAYBAN { get; set; }
        public Nullable<int> MAND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDTable> CTHDTables { get; set; }
        public virtual NGUOIDUNGTable NGUOIDUNGTable { get; set; }
    }
}
