//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGiay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBBanGiayEntities : DbContext
    {
        public DBBanGiayEntities()
            : base("name=DBBanGiayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHDTable> CTHDTables { get; set; }
        public virtual DbSet<GIAYTable> GIAYTables { get; set; }
        public virtual DbSet<HOADONTable> HOADONTables { get; set; }
        public virtual DbSet<NGUOIDUNGTable> NGUOIDUNGTables { get; set; }
        public virtual DbSet<SIZEGIAYTable> SIZEGIAYTables { get; set; }
        public virtual DbSet<THUONGHIEUTable> THUONGHIEUTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
