//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNGTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOIDUNGTable()
        {
            this.HOADONTables = new HashSet<HOADONTable>();
        }
    
        public int MAND { get; set; }
        public string TENND { get; set; }
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string TOKEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONTable> HOADONTables { get; set; }
    }
}
